name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NEXT_TELEMETRY_DISABLED: 1 # Disable Next.js telemetry
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Setup Next.js for GitHub Pages
        run: |
          # Create next.config.js if it doesn't exist
          if [ ! -f next.config.js ]; then
            echo "module.exports = { output: 'export', images: { unoptimized: true }, basePath: '/Akhil-Shibu', assetPrefix: '/Akhil-Shibu/' };" > next.config.js
          else
            # Backup original config
            cp next.config.js next.config.js.bak
            # Update config for GitHub Pages
            sed -i "s/module.exports = {/module.exports = { output: 'export', images: { unoptimized: true }, basePath: '\/Akhil-Shibu', assetPrefix: '\/Akhil-Shibu\/',/" next.config.js
          fi
      - name: Build with Next.js
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4